import { AiFillStar } from "react-icons/ai";
//https://tracxn.com/d/explore/high-tech-startups-in-ethiopia/__xGtGAogbMs377IuJDH20z5u4cEuWM7Hlw3NKrqFFrQw/companies
//https://tracxn.com/d/explore/media-entertainment-startups-in-ethiopia/__TnLk5UQmlekLLPSJEWL7KNJ8FU_sf3MvAL60eQTksoI/companies
const data = [
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTBAxGaoc_ukcBlnvDLc-JdeMrCX1ksEjdeA&s",
    title: "New entertainment",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    numOfVote: "$140,00",
    newPrice: "Domestic",
    company: "Pre-Startup",
    color: "black",
    category: "Entertainment",
    description:"I work in healthcare, currently as a medical practitioner. Interested in new advancements in technology and medicine",
    location:"Addis Ababa, Ethiopia",
    investmentRange:"0 - 900,000 birr",
    AreaOfExperties:"Medicine, Health Care, Primary Care, Public Health, Occupational Health, Health Program Planning" ,
    TotalRequired:"5000000 ",
    MinperInvestor:"25000",
    h1:"Next-gen mobile phone cloudPOS for tap to pay in eCommerce",
    h2:"Board and exited founder steeped in payment industry experience",
    h3:"Patents granted in 14 countries and pending across multiple geographies"
   },
   {
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL5_HwcLtbV_2t4Yir3p0wLMJYPgF8FVhcTQ&s',
    title: "Geonet Systems",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    numOfVote: "$140,00",
    newPrice: "Domestic",
    company: "Pre-Startup",
    color: "green",
    category: "Technology",
    description:"I work in healthcare, currently as a medical practitioner. Interested in new advancements in technology and medicine",
    location:"Addis Ababa, Ethiopia",
    investmentRange:"0 - 900,000 birr",
    AreaOfExperties:"Medicine, Health Care, Primary Care, Public Health, Occupational Health, Health Program Planning",
    TotalRequired:"5000000 ",
    MinperInvestor:"25000",
    h1:"Next-gen mobile phone cloudPOS for tap to pay in eCommerce",
    h2:"Board and exited founder steeped in payment industry experience",
    h3:"Patents granted in 14 countries and pending across multiple geographies"
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO0msgXIr6V5_osTq6GPcFhmz76uFpDhJz1g&s",
    title: "BeBlocky",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    numOfVote: "140,00",
    newPrice: "Domestic",
    company: "Profitable",
    color: "white",
    category: "Technology",
    description:"I work in healthcare, currently as a medical practitioner. Interested in new advancements in technology and medicine",
    location:"Addis Ababa, Ethiopia",
    investmentRange:"0 - 900,000 ",
    AreaOfExperties:"Medicine, Health Care, Primary Care, Public Health, Occupational Health, Health Program Planning",
    TotalRequired:"5000000 birr",
    MinperInvestor:"25000",
    h1:"Next-gen mobile phone cloudPOS for tap to pay in eCommerce",
    h2:"Board and exited founder steeped in payment industry experience",
    h3:"Patents granted in 14 countries and pending across multiple geographies"
  },
  {
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL5_HwcLtbV_2t4Yir3p0wLMJYPgF8FVhcTQ&s',
    title: "Geonet Systems",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    numOfVote: "$140,00",
    newPrice: "Domestic",
    company: "Pre-Startup",
    color: "green",
    category: "Technology",
    description:"I work in healthcare, currently as a medical practitioner. Interested in new advancements in technology and medicine",
    location:"Addis Ababa, Ethiopia",
    investmentRange:"0 - 900,000 birr",
    AreaOfExperties:"Medicine, Health Care, Primary Care, Public Health, Occupational Health, Health Program Planning",
    TotalRequired:"5000000 ",
    MinperInvestor:"25000",
    h1:"Next-gen mobile phone cloudPOS for tap to pay in eCommerce",
    h2:"Board and exited founder steeped in payment industry experience",
    h3:"Patents granted in 14 countries and pending across multiple geographies"
  },
  
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO0msgXIr6V5_osTq6GPcFhmz76uFpDhJz1g&s",
    title: "BeBlocky",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    numOfVote: "140,00",
    newPrice: "Domestic",
    company: "Profitable",
    color: "white",
    category: "Technology",
    description:"I work in healthcare, currently as a medical practitioner. Interested in new advancements in technology and medicine",
    location:"Addis Ababa, Ethiopia",
    investmentRange:"0 - 900,000 ",
    AreaOfExperties:"Medicine, Health Care, Primary Care, Public Health, Occupational Health, Health Program Planning",
    TotalRequired:"5000000 birr",
    MinperInvestor:"25000",
    h1:"Next-gen mobile phone cloudPOS for tap to pay in eCommerce",
    h2:"Board and exited founder steeped in payment industry experience",
    h3:"Patents granted in 14 countries and pending across multiple geographies"
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTBAxGaoc_ukcBlnvDLc-JdeMrCX1ksEjdeA&s",
    title: "New entertainment",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    numOfVote: "$140,00",
    newPrice: "Domestic",
    company: "Pre-Startup",
    color: "black",
    category: "Entertainment",
    description:"I work in healthcare, currently as a medical practitioner. Interested in new advancements in technology and medicine",
    location:"Addis Ababa, Ethiopia",
    investmentRange:"0 - 900,000 birr",
    AreaOfExperties:"Medicine, Health Care, Primary Care, Public Health, Occupational Health, Health Program Planning" ,
    TotalRequired:"5000000 ",
    MinperInvestor:"25000",
    h1:"Next-gen mobile phone cloudPOS for tap to pay in eCommerce",
    h2:"Board and exited founder steeped in payment industry experience",
    h3:"Patents granted in 14 countries and pending across multiple geographies"
   },
];

export default data;