version: '3.8'
services:
  is-dev-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wimagda
      POSTGRES_DB: ideaspring
    networks:
      - startgood
  is-test-db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wimagda
      POSTGRES_DB: ideaspring
    networks:
      - startgood
networks:
  startgood:
  